import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home({ data, title }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/about-us">About</a>
          <a href="/contact">Contact</a>
          <a href="/recipes">Recipes</a>
        </nav>
      </header>
      <main>
      {data?.map((recipe) => (
        <Link key={recipe.id} href={`/recipes/${recipe.id}`}>
          <Image
            height={300}
            width={300}
            alt={recipe.title}
            src={recipe.image}
          />
          <h2>{recipe.title}</h2> <p>{recipe.description}</p>
        </Link>
      ))}
    </main>
    <footer>
        <p> &copy; 2023 Heaven and Kitchen</p>
      </footer>
     </> 
  
  );
}

export async function getServerSideProps() {
  const { recipe_categories } = await import("/data/data.json");
  console.log(recipe_categories);
  return {
    props: {
      data: recipe_categories,
      title: "Heaven and Kitchen",
    },
  };
}